services:
  producer:
    image: node:14
    user: node
    working_dir: /home/node/app
    environment:
      - RABBITMQ_CONN_URL=amqp://user:password@rabbit:5672
    volumes:
      - ./:/home/node/app
    command: "node src/producer.js"
    restart: on-failure

  consumer:
    image: node:14
    user: node
    working_dir: /home/node/app
    environment:
      - RABBITMQ_CONN_URL=amqp://user:password@rabbit:5672
    volumes:
      - ./:/home/node/app
    command: "node src/consumer.js"
    restart: on-failure

  rabbit:
    image: rabbitmq:3-management
    container_name: rabbit
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - 8080:15672
      - 5672:5672
    volumes:
      - ./tmp/rabbitmq:/var/lib/rabbitmq
